music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'


urlpatterns = [
    # /music/
    url(r'^$', views.index, name='index'),

    # /music/742/
    url(r'^(?P<album_id>[0-9]+)/$', views.details, name='details'),

    # /music/<album_id>/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name="favorite"),
]

website/urls.py
from django.contrib import admin
from django.conf.urls import include, url


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models
# Red pk 1


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from .models import Album

class IndexViews(generic.ListView):
    template_name = '' \
                    ''

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" >
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!--Hearder-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}"> Viberr </a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" area-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" area-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" area-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li><li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" area-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
    </nav>

{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/boot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="sidebar.css">

</head>
<body>


  <div class="row">
      <div class="col-xs-12 col-md-6" style="background-color: coral">Phone enitre width,desktop half the width</div>
      <div class="col-xs-12 col-md-6" style="background-color: #c3a9ff">Phone enitre width,desktop half the width</div>
      <div class="col-xs-12 col-md-6" style="background-color: #a8570d">Phone enitre width,desktop half the width</div>

      <h3>nesting rows</h3>
      <div class="row">
          <div class="col-md-9" style="background: cornflowerblue; padding: 30px;" >
              Hey I went to the movies today
              <div class="row">
                  <div class="col-md-6" style="background: lightblue;">child 1</div>

              </div>

              <div class="row">

                  <div class="col-md-6" style="background: lightseagreen;">child 2</div>
              </div>
          </div>
      </div>



  </div>



</body>
</html>

music/templates/music/cssgrid.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vaibhav</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: auto;
        }
        .container li:nth-child(odd){
                background: #50f42c;
        }
        .container li:nth-child(even){
                background: #3228f4;
        }

        .container ul{
            width: 100%;
            list-style-type: none;
            display: inline-grid;
            grid-template-columns: repeat(6, 1fr);
            grid-template-rows: 2em 1em 1.5em;
            grid-gap: 1px;
        }

        .container li{

        }

    </style>
</head>
<body>
    <div class="container">
        <ul>
            <li>1</li>
            <li>2</li>
            <li>3</li>
            <li>4</li>
            <li>5</li>
            <li>6</li>
        </ul>
    </div>

</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}


{% block title %}Album Details{% endblock %}


{% block body %}
<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="https://www.iconsdb.com/icons/preview/yellow/star-xxl.png">
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="submit">
</form>
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}


{% block body %}
{% if all_albums %}
    <h3>Here are all my albums</h3>
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:details' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>You don't have any albums</h3>
{% endif %}
{% endblock %}

music/templates/music/my.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>
  <body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">


              <!--logo-->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a href="#" class="navbar-brand">Vaibhav</a>
          </div>
          <div class="collapse navbar-collapse" id="mainNavBar">
          <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li ><a href="#">About</a></li>
              <li ><a href="#">Contact</a></li>

          </ul>


          <ul class="nav navbar-nav navbar-right">
              <li><a href="#">Logout</a></li>
          </ul>
        </div>
        </div>

      </nav>
    <div class="container">
        <h2>Well's are section with borders and grey background</h2>
        <div class="well">Basic Well</div>
        <div class="well well-sm">Basic Well</div>
        <div class="alert alert-success">Congratulations, you just won the game</div>
        <div class="alert alert-info">
            <a href="#" class="close" data-dismiss="alert" aria-label="close"> &times;</a>Don't forget Kelly's birthday today
        </div>
        <div class="alert alert-info fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close"> &times;</a>fuck
        </div>
    </div>



  
  </body>
</html>

music/templates/music/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="sidebar.css">

</head>
<body>
    <div class="container">

        <h3>Log In Demo</h3>

        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#popUpWindow">Open Log In Window</button>

        <div class="modal fade" id="popUpWindow">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- header -->
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h3 CLASS="modal-title">Log In</h3>
                    </div>

                    <!-- body(form) -->
                    <div class="modal-body">
                        <form role="form">
                            <div class="form-group">
                                <input type="email" class="form-control" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Password">
                            </div>
                        </form>
                    </div>

                    <!-- button -->
                    <div class="modal-footer">
                        <button class="btn btn-primary btn-block">Log In</button>
                    </div>


                </div>
            </div>
        </div>
    </div>




</body>
</html>